#Arquivo de execução do Robot Framework em uma pipeline CI/CD no github

name: Amazon_testes CI

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configuração do Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Substitua 'x' pela versão do Python que você está usando

    - name: Instalação do Robot Framework
      run: |
        python -m pip install --upgrade pip
        python -m pip install robotframework

    - name: Execução do teste
      run: |
        robot "Automações RobotFramework/web-test/amazon_testes.robot"